# Copyright (c) 2010, Suryandaru Triandana. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=go-rabbit.googlecode.com/hg/crypto/rabbit
GOFILES=\
	rabbit.go\

include $(GOROOT)/src/Make.pkg
